[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "seebuoy"
author = "Nick Cortale"
author-email = "nickcortale@gmail.com"
home-page = "https://github.com/nickc1/seebuoy"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 1 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Data :: Buoy :: Oceanography",
]
requires = [
    "pandas",
    "requests"
]
description-file = "README.md"
requires-python = ">=3.6"

[tool.flit.metadata.urls]
Documentation = "https://github.com/nickc1/seebuoy"